runtime: nodejs16

basic_scaling:
  max_instances: 1
  idle_timeout: 60m


# env_variables:
#   CLOUD_SQL_USERNAME: root
#   CLOUD_SQL_PASSWORD: SeLav6}`ve~DCROq
#   CLOUD_SQL_DATABASE_NAME: dbQuark
#   CLOUD_SQL_CONNECTION_NAME: api-perfil:us-central1:db-plataforma-quark

# vpc_access_connector:
#   name: projects/api-perfil/locations/us-central1/connectors/connect-to-sql


